### PR TITLE
fix if statement subscription history

### PR DESCRIPTION
**Pull request by paulavidela**
Pull Request
**Are you a current Fivetran customer?** 
Paula, Aleph, Data team

**What change(s) does this PR introduce?** 
Clause ` {% if var('stripe__subscription_history', false) %} `was not working if database had 'subscription_history', change it to: 
`{% if var('stripe__subscription_history') is not none %}`

**Did you update the CHANGELOG?** 

- [ ] Yes

**Does this PR introduce a breaking change?**

- [ ] Yes (please provide breaking change details below.)
- [X] No  (please provide an explanation as to how the change is non-breaking below.)

**Did you update the dbt_project.yml files with the version upgrade (please leverage standard semantic versioning)? (In both your main project and integration_tests)** 

- [ ] Yes

**Is this PR in response to a previously created Bug or Feature Request**

- [ ] Yes, Issue/Feature [link bug/feature number here]
- [X] No 

**How did you test the PR changes?** 

 

- [ ] CircleCi  
- [X] Local (please provide additional testing details below)

**Select which warehouse(s) were used to test the PR**
 

- [X] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Provide an emoji that best describes your current mood**
 
:dancer:

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

### CODE REVIEW

**Comment by fivetran-joemarkiewicz** [comment]
Hi @paulavidela thanks so much for opening this PR! 

Looking further into this I am wondering why the original statement was not working 🤔. The logic should set the variable to `false` **only** if it is not declared. Are you declaring the variable as `true` in your root `dbt_project.yml`?

**Comment by paulavidela** [comment]
> Hi @paulavidela thanks so much for opening this PR!
> 
> Looking further into this I am wondering why the original statement was not working 🤔. The logic should set the variable to `false` **only** if it is not declared. Are overwriting this by declaring the variable as `true` in your root `dbt_project.yml`?

Thanks Joe! 
in dbt_project @ dbt_stripe_source we have: 
    subscription_history: "{{ source('stripe', 'subscription_history') }}"
    subscription: "{{ source('stripe', 'subscription') }}"
 
in dbt_project @ dbt_stripe we have: 
    subscription: "{{ ref('stg_stripe__subscription') }}"

It was failing because we have the table 'subscription_history' but not 'subscription' 

for some reason: 
even though we had the table _subscription_history_, `subscription_history: "{{ source('stripe', 'subscription_history') }}"` was not true so the model was looking for table _subscription_ and failing
We wanted the first statement to be true.

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for the additional details @paulavidela!

In order for the package to disable the `subscription` source, you will need to add the [stripe__subscription_history](https://github.com/fivetran/dbt_stripe_source#step-5-leveraging-subscription-vs-subscription-history-sources) variable to your root dbt_project.yml and set the value to be `true`.
```yml
vars:
    stripe__subscription_history: True
```

Would you mind setting this in your project and let me know if you still experience and error within the package.

**Comment by paulavidela** [comment]
> Thanks for the additional details @paulavidela!
> 
> In order for the package to disable the `subscription` source, you will need to add the [stripe__subscription_history](https://github.com/fivetran/dbt_stripe_source#step-5-leveraging-subscription-vs-subscription-history-sources) variable to your root dbt_project.yml and set the value to be `true`.
> 
> ```yaml
> vars:
>     stripe__subscription_history: True
> ```
> 
> Would you mind setting this in your project and let me know if you still experience and error within the package.

Thanks! Closing this PR

**Pull request closed without merging**
